import type { Metadata } from "next";
import type { ReactNode } from "react";
import ConditionalChatbase from "./components/ConditionalChatbase";
import Footer from "./components/Footer";
import { Geist, Geist_Mono } from "next/font/google";

import Navbar from "./components/Navbar";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConditionalChatbase />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
